k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /tmp/dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: true
    reactive: true
    defaultsToFullScreen: false
    skin: moonlight-wilmersdorf
  noIcons: true
  skipLatestRevCheck: false
  keepMissingClusters: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.36.1
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 200
    buffer: 500
    sinceSeconds: 300
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
